//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EasyCalcppc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_EASYCALC                    2
#define IDC_EASYCALC_ACCEL              3
#define IDI_EASYCALC                    101
#define IDR_MENU                        102
#define IDS_FILE                        103
#define IDS_HELP                        104
#define IDD_ABOUTBOX                    105
#define IDD_ABOUTBOX_WIDE               106
#define IDS_EDIT                        107
#define IDS_SPECIAL                     108
#define IDD_OPT_GENERAL                 131
#define IDD_OPT_SKINS                   132
#define IDD_RES_MENU                    134
#define IDD_VARENTRY                    136
#define IDD_SOLVER_CONFIG               137
#define IDD_EDITVAR                     138
#define IDD_DATAMGR                     139
#define IDD_EDITFCT                     140
#define IDD_LARGE_MENU                  141
#define IDD_SLIM_MENU                   142
#define IDD_OPT_PREFS                   145
#define IDD_ASKTXT                      146
#define IDD_LISTEDIT                    147
#define IDD_VARSTRINGENTRY              148
#define IDD_MATRIXEDIT                  149
#define IDD_SOLVER                      150
#define IDD_NOTES                       151
#define IDD_FINANCIALS                  152
#define IDD_GRAPH_PREFS                 153
#define IDD_GRAPH_CONFIG                154
#define IDD_GRAPH_CONFIGXY              155
#define IDB_BITMAP1                     156
#define IDB_BITMAP2                     157
#define IDC_STATIC_1                    201
#define IDC_STATIC_2                    202
#define IDC_STATIC_3                    203
#define IDC_CHECK_MOUSE                 1008
#define IDC_COMBO_SKIN1                 1010
#define IDC_COMBO_SKIN2                 1011
#define IDC_COMBO_SKIN3                 1012
#define IDC_COMBO_SKING                 1013
#define IDC_SKIN3                       1020
#define IDC_SKIN2                       1021
#define IDC_SKIN1                       1022
#define IDC_LIST_FV                     1023
#define IDC_SKING                       1023
#define IDC_LIST_RESM                   1034
#define IDC_VARCOMBO                    1037
#define IDC_DATALIST                    1043
#define IDC_NEW                         1044
#define IDC_MODIFY                      1045
#define IDC_UPDATE                      1047
#define IDC_CONFIG                      1048
#define IDC_NOTES                       1049
#define IDC_USERF                       1054
#define IDC_CALCF                       1055
#define IDC_PARAM                       1056
#define IDC_EDIT3                       1057
#define IDC_LIST_LARGE                  1058
#define IDC_LIST_SLIM                   1059
#define IDC_VAR                         1060
#define IDC_RADIAN                      1061
#define IDC_DEGREE                      1062
#define IDC_GRAD                        1063
#define IDC_DECIMAL                     1064
#define IDC_BINARY                      1065
#define IDC_OCTAL                       1066
#define IDC_HEXADECIMAL                 1067
#define IDC_SKINVAL                     1068
#define IDC_SKIN                        1069
#define IDC_PRECISION                   1070
#define IDC_PRECVAL                     1071
#define IDC_TRUNCPREC                   1072
#define IDC_INTEGERS                    1073
#define IDC_FORMATNUM                   1074
#define IDC_STRIP_0                     1075
#define IDC_SHOW_UNITS                  1076
#define IDC_OS_NUMPREFS                 1077
#define IDC_CALCGROUP                   1080
#define IDC_FORMATGROUP                 1081
#define IDC_MATCH_BKT                   1083
#define IDC_INS_HELP                    1084
#define IDC_ASSISTGROUP                 1085
#define IDC_VARNAME                     1088
#define IDC_MIN                         1089
#define IDC_VARNAME2                    1089
#define IDC_VARNAME4                    1089
#define IDC_TITLE                       1090
#define IDC_MAX                         1090
#define IDC_PREC                        1091
#define IDC_LANGUAGE_CB                 1093
#define IDC_LANGUAGE                    1094
#define IDC_EDIT2                       1095
#define IDC_INSERT                      1096
#define IDC_COMBO_LIST1                 1099
#define IDC_EDITLIST                    1101
#define IDC_COMBO_LIST2                 1102
#define IDC_COMBO_LIST3                 1103
#define IDC_APPEND                      1107
#define IDC_SUBITEMEDIT                 1108
#define IDC_DELETE                      1116
#define IDC_EDIT1                       1117
#define IDC_EDIT4                       1118
#define IDC_EDITMAX                     1119
#define IDC_SIP                         1120
#define IDC_EDITPREC                    1121
#define IDC_EDITTHSTEP                  1122
#define IDC_EDITMATRIX                  1128
#define IDC_COMBO_MATRIX                1129
#define IDC_COMBO_NBROWS                1130
#define IDC_COMBO_NBCOLS                1131
#define IDC_SOLVE                       1132
#define IDC_VARLIST                     1133
#define IDC_COMBO_WKSHT                 1134
#define IDC_EDITMIN                     1136
#define IDC_VARCOMMENT                  1137
#define IDC_EDITTHMAX                   1137
#define IDC_LIST1                       1138
#define IDC_EDITTHMAX2                  1138
#define IDC_EDITX6                      1138
#define IDC_ENDP                        1139
#define IDC_BEGINP                      1140
#define IDC_RADIO2                      1142
#define IDC_RADIOPOLAR                  1142
#define IDC_VARNAME3                    1143
#define IDC_XMIN                        1145
#define IDC_XMAX                        1146
#define IDC_YMIN                        1147
#define IDC_YMAX                        1148
#define IDC_THMIN                       1149
#define IDC_THMAX                       1150
#define IDC_THSTEP                      1151
#define IDC_EDITXMIN                    1152
#define IDC_EDITXMAX                    1153
#define IDC_EDITTHMIN                   1154
#define IDC_EDITYMIN                    1155
#define IDC_EDITYMAX                    1156
#define IDC_CHECKLOGX                   1157
#define IDC_EDITX1                      1157
#define IDC_CHECKLOGY                   1158
#define IDC_EDITX2                      1158
#define IDC_RADIOFCT                    1159
#define IDC_EDITX3                      1159
#define IDC_RADIOPARAM                  1160
#define IDC_EDITX4                      1160
#define IDC_BUTTONDEFAULT               1161
#define IDC_EDITX5                      1161
#define IDC_BUTTON2                     1162
#define IDC_BUTTONTRIGODEF              1162
#define IDC_STATICGRMODE                1163
#define IDC_Y6                          1169
#define IDC_CHECKY1                     1170
#define IDC_CHECKY2                     1171
#define IDC_CHECKY3                     1172
#define IDC_CHECKY4                     1173
#define IDC_CHECKY5                     1174
#define IDC_CHECKY6                     1175
#define IDC_COLORY1                     1176
#define IDC_COLORY2                     1177
#define IDC_COLORY3                     1178
#define IDC_COLORY4                     1179
#define IDC_COLORY5                     1180
#define IDC_COLORY6                     1181
#define IDC_LINEY1                      1182
#define IDC_LINEY2                      1183
#define IDC_LINEY3                      1184
#define IDC_LINEY4                      1185
#define IDC_LINEY5                      1186
#define IDC_LINEY6                      1187
#define IDC_BUTTONX1                    1189
#define IDC_BUTTONX2                    1190
#define IDC_EDITY5                      1191
#define IDC_EDITY6                      1192
#define IDC_EDITY1                      1193
#define IDC_BUTTONX3                    1194
#define IDC_EDITY2                      1195
#define IDC_BUTTONX4                    1196
#define IDC_EDITY3                      1197
#define IDC_BUTTONX5                    1198
#define IDC_EDITY4                      1199
#define IDC_BUTTONX6                    1200
#define IDC_BUTTON1                     1203
#define IDC_BUTTONY1                    1204
#define IDC_BUTTONY2                    1205
#define IDC_BUTTONY3                    1206
#define IDC_BUTTONY4                    1207
#define IDC_BUTTONY5                    1208
#define IDC_BUTTONY6                    1209
#define IDM_FILE_EXIT                   32777
#define IDM_EDIT_CLEARHISTORY           32782
#define IDM_EDIT_CLIPCUT                32784
#define IDM_EDIT_CLIPPASTE              32785
#define IDM_FILE_OPTIONS                32786
#define IDM_EDIT_CLIPCOPY               32787
#define IDM_EDIT_LISTEDITOR             32789
#define IDM_EDIT_MATRIXEDITOR           32791
#define IDM_SPECIAL_SOLVER              32793
#define IDM_SPECIAL_FINANCIALCALCULATOR 32794
#define ID_FILE_IMPORT                  32795
#define ID_FILE_EXPORT                  32796
#define ID_EXPORT_VARIABLES             32797
#define ID_EXPORT_FUNCTIONS             32798
#define ID_EXPORT_EQUATIONS             32799
#define IDM_FILE_IMPORT                 32800
#define IDM_EXPORT_VARIABLES            32801
#define IDM_EXPORT_FUNCTIONS            32802
#define IDM_EXPORT_EQUATIONS            32803
#define ID_Menu                         32804
#define IDM_EDIT_DATAMANAGER            32805
#define ID_HELP_HELP                    32806
#define IDM_HELP_HELP                   32807
#define IDM_OK                          40000
#define IDM_HELP                        40001
#define IDM_HELP_ABOUT                  40002
#define IDM_FILE                        40003
#define IDM_EDIT                        40004
#define IDM_SPECIAL                     40005
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1210
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
